import SlideRenderer from '@/components/slides/SlideRenderer';
import { THEMES } from '@/lib/themes';
import { STYLES } from '@/lib/styles';
import type { SlideData, Theme, StyleVariant } from '@/types/carousel';

// Sample slides covering all 9 types — real MLV content
const sampleSlides: SlideData[] = [
  {
    type: 'hook',
    headline: 'You don\'t need to learn to code to build an app.',
    sub: 'Here\'s how to ship a product this weekend.',
    cta: 'SWIPE →',
  },
  {
    type: 'step',
    num: '01',
    headline: 'Define the problem',
    body: 'Don\'t start with "I want to build an app."\n\nStart with: "What\'s a problem I see every day?"',
  },
  {
    type: 'split',
    headline: 'The old way vs. the new way',
    left: 'OLD WAY\n\nLearn Python — 6 months\nLearn a framework — 3 months\nBuild — 3 months\nShip — 1 year later',
    right: 'NEW WAY\n\nOpen Claude\nDescribe what you want\nCopy the code\nShip — this weekend',
  },
  {
    type: 'result',
    headline: 'What you now have',
    body: '✦ A live product\n✦ Real user feedback\n✦ A story for your college apps\n\nAll in one weekend.\nNo coding bootcamp required.',
  },
  {
    type: 'concept',
    label: 'Key concept',
    headline: 'Customer Discovery',
    body: 'The process of talking to potential users to understand their problems before building a solution.\n\nYou just did it without even knowing the term.',
  },
  {
    type: 'close',
    headline: 'Save this.\nTry it this weekend.',
    sub: 'Follow @mlvignite for more.',
    logo: true,
  },
  {
    type: 'close-cta',
    headline: 'Ready to build?',
    sub: 'Join 10,000+ student builders.',
    cta: 'Join MLV →',
    logo: true,
  },
  {
    type: 'quote',
    headline: 'The best way to predict the future is to build it.',
    sub: 'Alan Kay',
  },
  {
    type: 'text',
    headline: 'One more thing',
    body: 'This entire carousel was generated by the MLV Carousel Generator.\n\nPaste structured text. Get professional slides.\nNo design skills required.',
  },
];

const totalSlides = sampleSlides.length;
const theme: Theme = THEMES[0]; // MLV Dark
const style: StyleVariant = STYLES[0]; // Clean Step
const dims = { width: 1080, height: 1350 };
const previewScale = 0.4;

export default function Home() {
  return (
    <main
      style={{
        backgroundColor: '#08080C',
        minHeight: '100vh',
        padding: 32,
      }}
    >
      <h1
        style={{
          color: '#F5F5F5',
          fontSize: 24,
          fontWeight: 700,
          marginBottom: 8,
        }}
      >
        MLV Carousel Generator — Slide Preview
      </h1>
      <p
        style={{
          color: '#9CA3AF',
          fontSize: 14,
          marginBottom: 32,
        }}
      >
        All 9 slide types · MLV Dark theme · Clean Step style · {dims.width}×{dims.height} at {Math.round(previewScale * 100)}% scale
      </p>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(420px, 1fr))',
          gap: 32,
        }}
      >
        {sampleSlides.map((slide, i) => (
          <div key={i}>
            <div
              style={{
                color: '#6AC670',
                fontSize: 11,
                fontWeight: 500,
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                marginBottom: 6,
              }}
            >
              [{slide.type}] — Slide {i + 1}/{totalSlides}
            </div>
            <div
              style={{
                width: dims.width * previewScale,
                height: dims.height * previewScale,
                overflow: 'hidden',
                borderRadius: 8,
                border: '1px solid rgba(255,255,255,0.12)',
                position: 'relative',
              }}
            >
              <div
                style={{
                  transform: `scale(${previewScale})`,
                  transformOrigin: 'top left',
                }}
              >
              <SlideRenderer
                slide={slide}
                slideIndex={i}
                totalSlides={totalSlides}
                theme={theme}
                style={style}
                dimensions={dims}
                showLogo={false}
                fontScale={1}
              />
              </div>
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
