'use client';

import { useRef, useState, useCallback } from 'react';
import SlideRenderer from '@/components/slides/SlideRenderer';
import { THEMES } from '@/lib/themes';
import { STYLES } from '@/lib/styles';
import {
  exportSlide,
  exportAllAsZip,
  exportAsPdf,
  copySlideToClipboard,
} from '@/lib/export';
import type { SlideData, Theme, StyleVariant } from '@/types/carousel';

// Sample slides covering all 9 types — real MLV content
const sampleSlides: SlideData[] = [
  {
    type: 'hook',
    headline: "You don't need to learn to code to build an app.",
    sub: "Here's how to ship a product this weekend.",
    cta: 'SWIPE →',
  },
  {
    type: 'step',
    num: '01',
    headline: 'Define the problem',
    body: 'Don\'t start with "I want to build an app."\n\nStart with: "What\'s a problem I see every day?"',
  },
  {
    type: 'split',
    headline: 'The old way vs. the new way',
    left: 'OLD WAY\n\nLearn Python — 6 months\nLearn a framework — 3 months\nBuild — 3 months\nShip — 1 year later',
    right: 'NEW WAY\n\nOpen Claude\nDescribe what you want\nCopy the code\nShip — this weekend',
  },
  {
    type: 'result',
    headline: 'What you now have',
    body: '✦ A live product\n✦ Real user feedback\n✦ A story for your college apps\n\nAll in one weekend.\nNo coding bootcamp required.',
  },
  {
    type: 'concept',
    label: 'Key concept',
    headline: 'Customer Discovery',
    body: 'The process of talking to potential users to understand their problems before building a solution.\n\nYou just did it without even knowing the term.',
  },
  {
    type: 'close',
    headline: 'Save this.\nTry it this weekend.',
    sub: 'Follow @mlvignite for more.',
    logo: true,
  },
  {
    type: 'close-cta',
    headline: 'Ready to build?',
    sub: 'Join 10,000+ student builders.',
    cta: 'Join MLV →',
    logo: true,
  },
  {
    type: 'quote',
    headline: 'The best way to predict the future is to build it.',
    sub: 'Alan Kay',
  },
  {
    type: 'text',
    headline: 'One more thing',
    body: 'This entire carousel was generated by the MLV Carousel Generator.\n\nPaste structured text. Get professional slides.\nNo design skills required.',
  },
];

const totalSlides = sampleSlides.length;
const theme: Theme = THEMES[0]; // MLV Dark
const style: StyleVariant = STYLES[0]; // Clean Step
const dims = { width: 1080, height: 1350 };
const previewScale = 0.4;
const carouselTitle = 'How to build an app using Claude';

export default function Home() {
  const slideRefs = useRef<(HTMLDivElement | null)[]>([]);
  const [exporting, setExporting] = useState(false);
  const [exportStatus, setExportStatus] = useState('');

  const getSlideNodes = useCallback(() => {
    return slideRefs.current.filter(Boolean) as HTMLDivElement[];
  }, []);

  const handleExportZip = async () => {
    setExporting(true);
    setExportStatus('Exporting...');
    const nodes = getSlideNodes();
    const result = await exportAllAsZip(nodes, carouselTitle, theme.id, (cur, tot) => {
      setExportStatus(`Exporting ${cur}/${tot}...`);
    });
    if (result.success) {
      const msg = result.failedSlides.length > 0
        ? `Downloaded! (${result.failedSlides.length} slide(s) failed)`
        : 'Downloaded!';
      setExportStatus(msg);
    } else {
      setExportStatus(`Export failed: ${result.error}`);
    }
    setTimeout(() => setExportStatus(''), 3000);
    setExporting(false);
  };

  const handleExportPdf = async () => {
    setExporting(true);
    setExportStatus('Generating PDF...');
    const nodes = getSlideNodes();
    const result = await exportAsPdf(nodes, carouselTitle, theme.id, dims, (cur, tot) => {
      setExportStatus(`Rendering ${cur}/${tot}...`);
    });
    setExportStatus(result.success ? 'PDF downloaded!' : `PDF failed: ${result.error}`);
    setTimeout(() => setExportStatus(''), 3000);
    setExporting(false);
  };

  const handleExportSingle = async (index: number) => {
    const node = slideRefs.current[index];
    if (!node) return;
    setExporting(true);
    const slideNum = String(index + 1).padStart(2, '0');
    const result = await exportSlide(node, `slide-${slideNum}.png`);
    setExportStatus(result.success ? 'Slide downloaded!' : `Failed: ${result.error}`);
    setTimeout(() => setExportStatus(''), 3000);
    setExporting(false);
  };

  const handleCopySlide = async (index: number) => {
    const node = slideRefs.current[index];
    if (!node) return;
    setExporting(true);
    const slideNum = String(index + 1).padStart(2, '0');
    const result = await copySlideToClipboard(node, `slide-${slideNum}.png`);
    if (result.success) {
      setExportStatus(result.error === 'clipboard-fallback' ? 'Saved as file (clipboard unavailable)' : 'Copied!');
    } else {
      setExportStatus(`Copy failed: ${result.error}`);
    }
    setTimeout(() => setExportStatus(''), 3000);
    setExporting(false);
  };

  const btnStyle = {
    padding: '10px 20px',
    backgroundColor: '#6AC670',
    color: '#0A0A0A',
    border: 'none',
    borderRadius: 4,
    fontSize: 13,
    fontWeight: 600 as const,
    cursor: 'pointer' as const,
    fontFamily: 'inherit',
  };
  const btnGhostStyle = {
    ...btnStyle,
    backgroundColor: 'transparent',
    color: '#F5F5F5',
    border: '1px solid rgba(255,255,255,0.12)',
  };
  const btnSmallStyle = {
    ...btnGhostStyle,
    padding: '4px 10px',
    fontSize: 11,
  };

  return (
    <main style={{ backgroundColor: '#08080C', minHeight: '100vh', padding: 32 }}>
      <h1 style={{ color: '#F5F5F5', fontSize: 24, fontWeight: 700, marginBottom: 8 }}>
        MLV Carousel Generator — Slide Preview
      </h1>
      <p style={{ color: '#9CA3AF', fontSize: 14, marginBottom: 16 }}>
        All 9 slide types · MLV Dark theme · Clean Step style · {dims.width}×{dims.height} at {Math.round(previewScale * 100)}% scale
      </p>

      {/* Export buttons */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 32, alignItems: 'center' }}>
        <button style={btnStyle} onClick={handleExportZip} disabled={exporting}>
          Download All (ZIP)
        </button>
        <button style={btnGhostStyle} onClick={handleExportPdf} disabled={exporting}>
          Download as PDF
        </button>
        {exportStatus && (
          <span style={{ color: '#6AC670', fontSize: 13, fontWeight: 500 }}>
            {exportStatus}
          </span>
        )}
      </div>

      {/* Hidden full-size slides for export capture */}
      <div
        style={{
          position: 'absolute',
          left: -9999,
          top: 0,
          pointerEvents: 'none' as const,
        }}
        aria-hidden="true"
      >
        {sampleSlides.map((slide, i) => (
          <div
            key={`export-${i}`}
            ref={(el) => { slideRefs.current[i] = el; }}
          >
            <SlideRenderer
              slide={slide}
              slideIndex={i}
              totalSlides={totalSlides}
              theme={theme}
              style={style}
              dimensions={dims}
              showLogo={false}
              fontScale={1}
            />
          </div>
        ))}
      </div>

      {/* Visible preview grid */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(420px, 1fr))',
          gap: 32,
        }}
      >
        {sampleSlides.map((slide, i) => (
          <div key={i}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
              <div
                style={{
                  color: '#6AC670',
                  fontSize: 11,
                  fontWeight: 500,
                  textTransform: 'uppercase' as const,
                  letterSpacing: '0.1em',
                }}
              >
                [{slide.type}] — Slide {i + 1}/{totalSlides}
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                <button style={btnSmallStyle} onClick={() => handleCopySlide(i)} disabled={exporting}>
                  Copy
                </button>
                <button style={btnSmallStyle} onClick={() => handleExportSingle(i)} disabled={exporting}>
                  PNG
                </button>
              </div>
            </div>
            <div
              style={{
                width: dims.width * previewScale,
                height: dims.height * previewScale,
                overflow: 'hidden',
                borderRadius: 8,
                border: '1px solid rgba(255,255,255,0.12)',
                position: 'relative',
              }}
            >
              <div
                style={{
                  transform: `scale(${previewScale})`,
                  transformOrigin: 'top left',
                }}
              >
                <SlideRenderer
                  slide={slide}
                  slideIndex={i}
                  totalSlides={totalSlides}
                  theme={theme}
                  style={style}
                  dimensions={dims}
                  showLogo={false}
                  fontScale={1}
                />
              </div>
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
